### ISSUE TITLE
build crashes when decoding script output to utf-8

### ISSUE THREAD

**Issue by micahsnyder** [Cisco-Talos/Mussels#25]
Issue reported in Discord chat by user "the_bob", compiling ClamAV on win10, installed the latest nasm, strawberry perl, msvc2017 and cmake 3.15.6.

User installed mussels to make building clamav easier, but it crashes pretty early into the build process
```
Traceback (most recent call last):
  File "[...]\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "[...]\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\[...]\Python37\Scripts\mussels.exe\__main__.py", line 9, in <module>
  File "C:\[...]\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\[...]\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\[...]\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\[...]\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\[...]\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\[...]\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\[...]\mussels\__main__.py", line 505, in build_alias
    ctx.forward(recipe_build)
  File "C:\[...]\click\core.py", line 573, in forward
    return self.invoke(cmd, **kwargs)
  File "C:\[...]\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\[...]\mussels\__main__.py", line 301, in recipe_build
    recipe, version, cookbook, target, results, dry_run, rebuild
  File "C:\[...]\mussels\mussels.py", line 1040, in build_recipe
    clean,
  File "C:\[...]\mussels\mussels.py", line 561, in _build_recipe
    if not recipe_object._build(clean):
  File "C:\[...]\mussels\recipe.py", line 419, in _build
    if not self._run_script(self.target, "make", build_scripts["make"]):
  File "C:\[...]\mussels\recipe.py", line 303, in _run_script
    self.logger.debug(line.decode("utf-8").strip())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 59: invalid start byte
```
from recipe.py it looks like it's choking on some bad output from one of the build scripts
```python
        # Run the build script.
        process = subprocess.Popen(
            os.path.join(os.getcwd(), script_name),
            shell=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        with process.stdout:
            for line in iter(process.stdout.readline, b""):
                self.logger.debug(line.decode("utf-8").strip()) #<-- line 303
```

---

May be a locale issue?
Changing `line.decode("utf-8")` to `line.decode("utf-8", "ignore")` appears to resolve the issue.

**Comment by bruce28** [comment]
does that changes anything? Is there more raw approach to decode and deal with utf8? ignore attribute, just make the code more dependent on that function. Any solution to go round that?

**Comment by micahsnyder** [comment]
@bruce28 perhaps it would be more correct to do `errors='replace'` instead of `errors='ignore'`
